apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: nodejs-opentelemetry-github
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: nodejs-opentelemetry-github
    eventName: nodejs-opentelemetry
  - name: pipeline
    eventSourceName: nodejs-opentelemetry-github
    eventName: nodejs-opentelemetry
  triggers:
  - template:
      name: payload
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: payload-
              labels:
                app: payload
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args: ["This is the message you sent me:\n", ""]
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.zen
            dest: spec.containers.0.args.1
  - template:
      name: pipeline
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: nodejs-opentelemetry-
              namespace: argo
            spec:
              entrypoint: build
              serviceAccountName: argo
              volumes:
              - name: kaniko-secret
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              templates:
              - name: build
                dag:
                  tasks:
                  - name: build-container-image
                    templateRef:
                      name: container-image
                      template: build-kaniko-git
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: app_repo
                        value: git://github.com/itamar-marom/nodejs-opentelemetry
                      - name: container_image
                        value: maromitamar/nodejs-opentelemetry
                      - name: container_tag
                        value: "latest"