apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: development

configMapGenerator:
  - name: nodejs-opentelemetry
    behavior: replace
    literals:
    - PORT=8080
    options:
      disableNameSuffixHash: true