apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: itamar

configMapGenerator:
  - name: nodejs-opentelemetry
    literals:
    - PORT=8080
    options:
      disableNameSuffixHash: true